version: "3.7"
networks:
  localdev:
volumes:
  rabbitmqdata:
    external: true
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "P@ssw0rd"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - localdev
    ports:
      - "5672:5672"
      - "15672:15672"